Repository openshift/custom-domains-operator, pull requests merged in 2020-11, with the labels that each got.

#12 Boilerplate Update To 341741919408921fbfaf5a3b4e0d2246a2efd23c
  .ci-operator.yaml
  .codecov.yml
  Makefile
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/boilerplate-commit
  boilerplate/_lib/boilerplate.mk
  boilerplate/_lib/common.sh
  boilerplate/_lib/ensure.sh
  boilerplate/_lib/freeze-check
  boilerplate/_lib/release.sh
  boilerplate/generated-includes.mk
  boilerplate/openshift/golang-osd-operator/.ci-operator.yaml
  boilerplate/openshift/golang-osd-operator/.codecov.yml
  boilerplate/openshift/golang-osd-operator/README.md
  boilerplate/openshift/golang-osd-operator/codecov-secret-mapping
  boilerplate/openshift/golang-osd-operator/codecov.sh
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/golangci.yml
  boilerplate/openshift/golang-osd-operator/operator-sdk-generate.sh
  boilerplate/openshift/golang-osd-operator/project.mk
  boilerplate/openshift/golang-osd-operator/prow-config
  boilerplate/openshift/golang-osd-operator/py-requirements.txt
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/openshift/golang-osd-operator/update
  boilerplate/openshift/golang-osd-operator/validate-yaml.py
  boilerplate/openshift/golang_osd_cluster_operator/README.md
  boilerplate/openshift/golang_osd_cluster_operator/golangci.yml
  boilerplate/openshift/golang_osd_cluster_operator/includes.mk
  boilerplate/openshift/golang_osd_cluster_operator/standard.mk
  boilerplate/openshift/golang_osd_cluster_operator/update
  boilerplate/update
  boilerplate/update.cfg
  build/Dockerfile
Labels: approved, lgtm

#13 Add bp related folders to .gitignore
  .gitignore
Labels: approved, lgtm

#14 Add OLM Bundle Scripts And Templates
  Makefile
  cmd/manager/main.go
  deploy/02_role.yaml
  hack/app_sre_build_deploy.sh
  hack/generate-operator-bundle.py
  hack/generate_template.py
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/csv.yaml
  hack/templates/package.yaml
  hack/templates/selectorsyncset.yaml
  hack/templates/template.yaml
  pkg/controller/customdomain/customdomain_controller_test.go
Labels: approved, lgtm, tide/merge-method-squash

#15 Fix path to generate-operator-bundle.py
  Makefile
Labels: approved, lgtm

#16 Make docker-build a dependency of skopeo-push
  Makefile
Labels: approved, lgtm

#17 Boilerplate: Update to 4216e7d2561ba153d816dff6f9d4f96e140b4e0d
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/common.sh
Labels: approved, lgtm

#19 Use standard app_sre_* scripts for bundle build and deployment
  Makefile
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#20 Bring generate-operator-bundle.py up to standards
  hack/generate-operator-bundle.py
Labels: approved, lgtm

#21 Move csv template to standard location.
  config/templates/custom-domains-operator-csv-template.yaml
Labels: approved

#22 Fix deploy/ file refs
  hack/generate-operator-bundle.py
Labels: approved

#24 Fix OLM template
  hack/generate_template.py
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, tide/merge-method-squash

#25 Ensure namespace exists
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#23 CR Status Changes
  cmd/manager/main.go
  deploy/crds/managed.openshift.io_customdomains_crd.yaml
  pkg/apis/customdomain/v1alpha1/customdomain_types.go
  pkg/controller/customdomain/customdomain_controller.go
  pkg/controller/customdomain/customdomain_utils.go
Labels: approved, lgtm

#26 Managed IngressController Pre-Checks
  pkg/apis/customdomain/v1alpha1/customdomain_types.go
  pkg/controller/customdomain/customdomain_controller.go
  pkg/controller/customdomain/customdomain_controller_test.go
  pkg/controller/customdomain/customdomain_utils.go
Labels: approved, lgtm, tide/merge-method-squash
