Repository openshift/custom-domains-operator, pull requests merged in 2023-12, with the labels that each got.

#146 boilerplate update
  .ci-operator.yaml
  OWNERS_ALIASES
  api/v1alpha1/zz_generated.deepcopy.go
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/subscriber-report
  boilerplate/openshift/golang-osd-operator-osde2e/test-harness-template.yml
  boilerplate/openshift/golang-osd-operator/OWNERS_ALIASES
  boilerplate/openshift/golang-osd-operator/README.md
  boilerplate/openshift/golang-osd-operator/configure-fips.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/common-generate-operator-bundle.py
  boilerplate/openshift/golang-osd-operator/csv-generate/common.sh
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.mk
  boilerplate/openshift/golang-osd-operator/csv-generate/csv-generate.sh
  boilerplate/openshift/golang-osd-operator/project.mk
  boilerplate/openshift/golang-osd-operator/standard.mk
  build/Dockerfile
  deploy/crds/managed.openshift.io_customdomains.yaml
  osde2e/test-harness-template.yml
Labels: approved, lgtm, tide/merge-method-squash

#147 Update dependencies to k8s v0.27.8
  go.mod
  go.sum
Labels: approved, lgtm

#148 SDCICD-1178: remove affinity/tolerations from CatalogSource
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, jira/valid-reference
